add: do not deserialize when topics schemas differ
streamnative/pulsar-spark pull request #61
Opened 2021-09-30 10:36 UTC by atezs82

This PR extends the connector with a boolean parameter (`deserializePayload`), using which users can skip de-serialization if we intend to read topics with multiple different schemas - by just adding an empty schema to the topic and giving back raw values upon de-serialization (that code part could remain unchanged).

**Driving usecase**: we are using the connector for reading DB table change events from Pulsar (using a single topic for a table). Since the data flow is not constant across tables (some of them has a very low inflow, while others might contain high amounts of data) we would like to create a single Spark streaming job for them. This is needed to process this data more efficiently. On the other hand, the connector cannot handle this, since different topics having the DB table change events have different schemas (this schema actually contains the columns of the tables).

Please let me know if you find this approach usable, I can add unit tests, documentation as well to the PR if you think that we can proceed with this. Existing feature will not be changed, this will be an additional parameter that users of the connector can set if needed.

Moreover, there are some utility methods (eg. `SchemaUtils.pulsarSourceSchema()`) which, if exposed and documented properly, can help users to convert their messages easier (they basically do not have to write the same after fetching the topic schemas from Pulsar). What do you think about exposing these from the connector? (By importing the Pulsar connector they can be used right away.) (In order to make de-serialization easier for users we can also store the schema for the topic next to each raw value but that is not desirable since it would greatly increase the size of messages.)

2021-11-10 04:14 UTC, nlu90 requested changes

2021-11-10 04:14 UTC, nlu90 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
@atezs82  thanks for your contribution.

1. Given the behavior is actually allowing different schemas for topics. Can we rename the variable to `allowDifferentTopicSchemas`?

2. In the case that an empty schema info is returned. Will any deserialization happen for your use case that the DB cdc events coming? And will there be any exceptions?

2021-11-10 16:18 UTC, atezs82 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
Thanks for your review!

1. Thanks for the idea, that is a better naming indeed. Will make that change.
2. Not sure if I get the question right, but if the schema is empty then "deserialization" will be not in effect. (As far as I understand this will be used instead: https://github.com/streamnative/pulsar-spark/blob/master/src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala#L89 .) Now this is questionable, but it seemed to be a way forward consuming multiple, different topics from within a single connector with only a very limited change in code (and preserving the original functionality). For our DB CDC use-case this seems to work in our proof-of-concept solution (and we need this, since DB tables are very different in schema and update frequency - we can have multiple parallel ETLs for each table but it is not always resource effective). Did I get your question right? What is your opinion on this?

2021-11-10 23:26 UTC, nlu90 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
@atezs82 

A more direct question is can the connector work as expected in your cdc case? My feel is there'll be some issues correctly parsing the events later.

2021-11-11 07:33 UTC, atezs82 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
Yes, it can work. On the other hand, the raw values are returned, so it is the responsibility of the downstream ETL logic to distinguish between individual topic messages (the name of the topic is in the output already) and deserialize/handle them properly (since only the raw `value` column is returned). In our PoC usecase that's what we do for now.

On the other hand, this responsibility need to be clearly stated in the documentation so that users are not confused. I tried to emphasize it here: https://github.com/streamnative/pulsar-spark/pull/61/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R417 - but we might be even more clear than this (maybe add some simple examples). Do you think that it would help?

2021-11-11 22:05 UTC, nlu90 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
I think this should be fine. 

Also, could you double-check all the `deserializePayload` is changed to `allowDifferentSchemas`?

2021-11-12 09:23 UTC, atezs82 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
Sure, will do that. Thanks!

2021-11-12 19:44 UTC, nlu90 commented
@atezs82 could you fix the coding style issues so that we can merge this change?

2021-11-12 20:06 UTC, atezs82 commented on src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
> +    deserializePayload match {
Also did that, see the latest commit.

2021-11-12 20:12 UTC, atezs82 commented
@nlu90 Just did that, and fixed the merge conflict as well.

By the way, do you see this as a problem? If yes, shall we address it in this PR or shall we handle it elsewhere?

> Moreover, there are some utility methods (eg. SchemaUtils.pulsarSourceSchema()) which, if exposed and documented properly, can help users to convert (deserialize) their messages easier (they basically do not have to write the same after fetching the topic schemas from Pulsar). What do you think about exposing these from the connector? (By importing the Pulsar connector they can be used right away.) (In order to make de-serialization easier for users we can also store the schema for the topic next to each raw value but that is not desirable since it would greatly increase the size of messages.)

2021-11-12 20:58 UTC, nlu90 commented
@atezs82 Let's handle the exposing utility API in a separate place. We can first create issue for discussing what apis are needed to be exposed.

I'm not a fan for storing scheme next to each raw value as the reason you mentioned

2021-11-12 20:58 UTC, nlu90 approved these changes

2021-11-13 10:21 UTC, atezs82 commented
Ok, thanks, will create that issue then.

2021-11-16 01:49 UTC, syhily commented
LGTM

2021-11-16 01:49 UTC, syhily approved these changes

2021-11-16 01:50 UTC, merged